.travis.maven_config.yml
Eliminate experimental `DeployAtEnd` flag: https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#deployAtEnd
The latest green build of `alfresco-process` didn't deploy any artifact to nexus: https://travis-ci.com/github/Alfresco/alfresco-process/builds/224535976
Actually, none of the artifacts of `alfresco-process` M12 are present in nexus
=> AAE-5058 Allow new starter artifacts to be published in nexus

.travis.checkov_install.yml
Forces checkov2 installation to happen with  python3.9 and avoid running during others stages thatn linters.
=> OPSEXP-1266: checkov2 makes sense for lint stages only with python 3.8+

.github/actions/calculate-next-internal-version/action.yml, .github/actions/calculate-next-internal-version/next-prerelease.sh
The next version should be provided as input and based on that the next prerelease version is calculated. I.e:
```yaml
uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@revision
with:
next-version: 7.2.0
```
=> fix: AAE-7879 use semver to calculate next prerelease

README.md
Currently in use on https://github.com/Alfresco/alfresco-ansible-deployment
=> Add community action for retrying commands

README.md
I've enabled codacy integration and fixed up a bunch of small markdown issues
=> [minor] Fixup codacy issues

.github/workflows/publish-artifacts-for-veracode.yml
there is no need for running pre-commit, as this is already checked in the main build
=> AAE-8962 fix build for Veracode

.github/workflows/versions-propagation-auto-merge.yml
`github.actor` references the user who triggered the workflow, that could be a different user in case of rebase for instance.
Note that a rebase is mandatory in case where another PR got merged in the main branch in the mean time.
What we are looking is actually the author of the PR, so `github.event.pull_request.user.login`
=> AAE-9367 fix condition for auto-merge

.github/actions/calculate-next-internal-version/action.yml, .github/actions/calculate-next-internal-version/next-prerelease.sh
An extra input defines the type of the prerelease. i.e. `alpha` (default), `beta`, `rc`.
It's also possible to define a working directory to point to the git repository.
=> AAE-8916 Add the possibility to specify the type of the prerelease

.github/actions/dbp-charts/verify-compose/action.yml
Now the action relies on passing valid container registry credentials instead of checking the github event type.
=> OPSEXP-1545 Fix compose tests for forked PRs

.github/actions/pre-commit/action.yml
Ref: OPSEXP-1746
The goal is to use relevant pre-commit hooks in relevant workflows, but also offer any other option.
Also bumped the pre-commit to new major v3. Althoug hthis is a new major interface looks similar, they only moved from a js action to a composite one.
=> OPSEXP-1746: allow passing additional args to pre-commit

.github/actions/helm-unit-tests/action.yml, README.md
Ref: OPSEXP-1746
installs `helm-unittest` plugin and runs tests if a `tests` folder exists
=> OPSEXP-1746: add an helm-unittest action

.github/actions/jx-updatebot-pr/action.yml, README.md
This PR adds reusable Github Action for promoting release versions via pull requests on the downstream repositories using jx-updatebot. 
See https://github.com/jenkins-x-plugins/jx-updatebot for details
=> fix(AAE-10901): add jx-updatebot-pr Github Action

.github/actions/dbp-charts/verify-helm/helm_install.sh
* have a different namespace when building a matrix, so parallelization is an option
* increase retry timeout for test - to give more time to flaky things to settle up and for manual inspection
* remove hard sleep before executing tests since we are already retrying them automatically
* remove unnecessary cleanup in pods_ready function
* bump ingress-nginx to version 4.2.5
OPSEXP-1777
=> OPSEXP-1777 Fixup verify-helm action

.github/actions/automate-dependabot/action.yml, .github/actions/automate-propagation/action.yml, .github/actions/calculate-next-internal-version/next-prerelease.sh, .github/actions/git-check-existing-tag/action.yml, .github/actions/git-latest-tag/action.yml, .github/actions/helm-package-chart/action.yml, .github/actions/helm-parse-next-release/action.yml, .github/actions/load-release-descriptor/action.yml, .github/actions/maven-build-and-tag/action.yml, .github/actions/nexus-create-staging/action.yml, .github/actions/publish-helm-chart/action.yml, .github/actions/resolve-preview-name/resolve-preview-name.sh, .github/actions/send-slack-notification/action.yml, .github/actions/update-pom-to-next-pre-release/action.yml
Support for the `set-output` [replacement](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)
Done with search `echo "::set-output name=(.*)::(.*)"` and replace with `echo "$1=$2" >> $GITHUB_OUTPUT` in vscode
OPSEXP-1772
=> OPSEXP-1772 Migrate to new way to set outputs in our actions

.github/actions/jx-updatebot-pr/action.yml
This PR updates x-updatebot-pr release binary version to 0.3.13 with the fix https://github.com/jenkins-x-plugins/jx-updatebot/pull/57
This will fix propagation jobs in https://github.com/Alfresco/alfresco-process/actions/runs/3299923763/jobs/5444513209
=> fix(jx-updatebot-pr): update release binary version to 0.3.13 

.github/actions/send-slack-notification/action.yml, .github/actions/send-slack-notification/compute-message.sh, .github/actions/send-slack-notification/tests/send-slack-notification.bats, .github/workflows/test.yml
=> OPSEXP-1806 Fix multiline/markdown support in slack notification

.github/actions/maven-deploy-file/action.yml
```
Error:  The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/imagemagick-build/imagemagick-build). Please verify you invoked Maven from the correct directory. -> [Help 1]
```
https://github.com/Alfresco/imagemagick-build/actions/runs/3436052143/jobs/5729132434#step:7:39
=> Fix failure in maven-deploy-file

.github/actions/update-pom-to-next-pre-release/action.yml
Part of https://alfresco.atlassian.net/browse/AAE-11332
=> fix(AAE-11332): add prerelease-type input to update-pom-to-next-prerelease action

.github/actions/maven-deploy-file/action.yml
OPSEXP-1833
can't find a proper way to build a command line with arguments that get escaped - so for now I prefer to avoid using double quotes and at least it will work if argument values doesn't contains a space.
=> OPSEXP-1833 Really fix maven-deploy-file

.github/workflows/test.yml, .pre-commit-config.yaml
- Update to v0.19.2 (latest)
- Add check-dependabot to validate dependabot config
---
👋 Hi there, `check-jsonschema` maintainer here!
I received a PR in reference to #178 on this repo, and the relevant fix has already been included and released in the latest `check-jsonschema` version (v0.19.2). I noticed that this repo is on a somewhat older version of the hook, so it seemed like a nice/friendly thing to drop a PR with the relevant update.
I recommend using `pre-commit autoupdate` regularly, or using pre-commit.ci for its autoupdate functionality, as it will help you stay up-to-date.
=> Update check-jsonschema usage

.github/actions/setup-helm-docs/action.yml
OPSEXP-1581
beware that this will trigger a pre-commit failure because helm-docs put the version in the footer of the generated markdown
=> OPSEXP-1581 Bump helm-docs default version to v1.11.0

.github/actions/helm-release-and-publish/action.yml
This PR adds missing input params to helm-release-and-publish action to be able to reuse it in https://github.com/Alfresco/alfresco-process-infrastructure-deployment/pull/825
=> fix(AAE-11371): update helm-release-and-publish input params 

.github/actions/maven-build-and-tag/action.yml
The new `verbose` input should allow us to debug issues related to maven downloads.
=> AAE-11466: allow showing maven downloads on build-and-tag action

.github/actions/maven-build-and-tag/action.yml
Acceptance tests does not produce any docker images, so we need to be able to skip this step
=> AAE-11373 add possibility to skip docker build

.github/actions/send-slack-notification/action.yml, .github/actions/send-slack-notification/compute-message.sh, .github/actions/send-slack-notification/tests/send-slack-notification.bats
- fix information displayed depending on event use cases (push, pull_request, schedule, workflow_dispatch)
- fix management of messages with quotes
- improve overall display
=> AAE-11711: Improve slack notification payload

.github/actions/send-slack-notification/action.yml
The main text was missing from the payload: the API was generating warnings because of that:
```
[WARN]  web-api:WebClient:0 The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
```
I just moved existing content around to make the message more compact and closer to other github skack notifications.
Here's a sample test notification:
=> AAE-11711: add text on slack notif payload

.github/actions/dbp-charts/verify-helm/helm_install.sh
We changed the way persistence values needs to be passed to render helm charts
`.persistence` => `.component.presistence`
See [acs-deployment documentation](https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/storage.md)
=> OPSEXP-1584: use new values for persistence

.github/actions/configure-git-author/action.yml, docs/README.md
Added the `global` input for `configure-git-author` action to enable `--global` option if needed.
=> ACS-4245 Add 'global' option for configure-git-author action

.github/actions/dbp-charts/verify-helm/helm_install.sh
Ref: OPSEXP-1761
Tried it with maximum concurrency: https://github.com/Alfresco/acs-deployment/pull/836/checks
[OPSEXP-1761]: https://alfresco.atlassian.net/browse/OPSEXP-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OPSEXP-1761: use per-LB sg annotation (-extra-security-groups)

.github/actions/get-build-info/action.yml, docs/README.md
Contributing the `get-build-info` action to load generically named env vars with build-related information. This is particularly useful for repositories that contain scripts relying on Travis/GitHub specific env variables and should rather rely on more abstract env variables to mitigate migration impacts in the future.
=> ACS-3844 Contribute get-build-info to alfresco-build-tools

.github/actions/veracode/action.yml, .github/actions/veracode/source_clear.sh, docs/README.md
I think it'd be safer to err on the side of caution and cause the builds to fail by default if the Veracode scan reports critical vulnerabilities or fails completely.
Also, given that the default value is to ignore failures, people trying to adopt the Veracode action often don't even realize that they're missing critical components to make the Veracode action work _(e.g.: the `SRCCLR_API_TOKEN` secret may be missing in the repository configuration, but it won't be very evident as the job goes green anyways)_.
It would be great to release this change before we start introducing the Veracode action into more repositories, so it won't be as impacting.
=> ACS-3750 Set default veracode-fails-build to 'true'

.github/actions/setup-java-build/action.yml, docs/README.md
Installs a custom `settings.xml` file in the Maven home directory. Does not fail in case the file is not found, as not all repositories may need to install the custom file.
**Sample run**: https://github.com/Alfresco/alfresco-enterprise-repo/pull/1221
=> ACS-4455 Install custom settings.xml as part of setup-java-build

.github/workflows/build-and-release-maven.yml
Adding a reusable workflow to match the most common Travis workflow we have at the moment, which seems to simply be build _(sometimes with tests)_ -> release.
Example of usage: https://github.com/Alfresco/alfresco-tas-ftp-test/actions/runs/4016617042
**Note:** this is a work in progress, and will be merged only once most if not all repositories that should use such a basic workflow have been tested and therefore the workflow has become at least abstract enough to be utilized properly within all ACS repositories with similar, simple workflows.
=> ACS-4456 Add reusable workflow for basic Maven build and release

.github/workflows/build-and-release-maven.yml
Private repository releases with the `build-and-release-maven.yml` workflow fail due to missing username.
=> ACS-4456 Fix private repository releases with reusable workflow

.github/workflows/build-and-release-maven.yml
=> ACS-3750 Use correct Git token for reusable workflow releases

.github/actions/maven-build-and-tag/action.yml, .github/actions/maven-update-pom-version/action.yml, .github/actions/update-pom-to-next-pre-release/action.yml, docs/README.md
When a PR is created with `preview` label, the build creates and publishes maven versions and docker images for the project with a snapshot tag `0.0.1-${GITHUB_PR_NUMBER}-${GITHUB_RUN_NUMBER}-SNAPSHOT`. Tested e.g. on https://github.com/Alfresco/alfresco-deployment-service/pull/996
=> [AAE-11861] add 'Create preview' feature

.github/workflows/build-and-release-maven.yml
Fix DependaBot PRs requiring unnecessary secrets since they won't be releasing anything.
**Example failure**: https://github.com/Alfresco/alfresco-jmx-logger/actions/runs/4242235129
**Fix test**: https://github.com/Alfresco/alfresco-jmx-logger/actions/runs/4242448707/jobs/7373964502
=> ACS-4506 Fix build-and-release-maven workflow DependaBot PRs

.github/actions/helm-plugin/action.yml, .github/actions/helm-unit-tests/action.yml, docs/README.md
Ref: OPSEXP-1853
The helm3-unittest plugin we introduced is now superseeded by the helm-unitest one. Instead of introducing a feature flip to choose which unittest plugin I prefer introducing a generic plugin install action and deprecate the old one.
=> OPSEXP-1853: add an helm plugin action

.github/actions/maven-build-and-tag/action.yml
Add option to enable reuse of testcontainers to speed up build process.
Documented feature: https://alfresco.atlassian.net/wiki/spaces/HXP/pages/1275265126/PoC+Parallel+Testing+Multi-Thread+Maven+Build#TestContainers-Reuse
=> AAE-13340 enable testcontainers reuse

.github/workflows/publish-artifacts-for-veracode.yml
This PR fix the failing workflow due to java 11, so this will change it to java 17
=> [AAE-15706] Change java version for failing workflow

.github/pull_request_template.md
- Jira Reference (also in PR title): OPSEXP-2225
- [README](/docs/README.md) updated after adding/changing behaviour of an action
- Proposed version increment for [release](/docs/README.md#release):
Current links are pointing to https://github.com/docs/README.md 😕
=> OPSEXP-2225 Fixup links in PR template

docs/README.md
- Jira Reference (also in PR title): OPSEXP-2328
Add github.workflow variable to avoid grouping different workflows when running at the same time in the same repo
=> OPSEXP-2328 Improve concurrency docs

docs/README.md
Removed not really useful anymore badges, add new one with latest release and number of contributors
=> Update README badges

.github/dependabot.yml, update-dependabot.sh
Instead of:
we'll get a single PR with both updates, but only for updates within the same action.
=> Reduce dependabot PRs for our actions by grouping updates

docs/README.md
Add generate-dependabot-glob-action documentation to _GitHub Actions provided by community_ section.
=> docs: add generate-dependabot-glob-action in readme

.github/actions/github-check-upcoming-runs/action.yml
Revealed by https://github.com/Alfresco/alfresco-build-tools/pull/521
No need to release a new version either
- Jira Reference (also in PR title): AAE-20726
=> AAE-20726 Fix version ref to inner action

.github/workflows/release.yml
- Jira Reference (also in PR title):
Release for https://github.com/Alfresco/alfresco-build-tools/pull/528 did not kick in (because of skip ci marker in one of the commits?) this allows unblocking
=> AAE-20957 Allow releasing on workflow_dispatch

.github/actions/install-galaxy-deps/action.yml, docs/README.md
- Jira Reference (also in PR title): OPSEXP-2743
- External PR link where changes has been tested: https://github.com/Alfresco/devops-engineering-iac/pull/87
=> OPSEXP-2743 Run ansible-galaxy via pipenv when available

update-dependabot.sh
without `yq` installed you end up with an empty dependabot config after running it without any error.
=> Ensure yq installed for dependabot pre-commit to work

.github/actions/setup-pysemver/action.yml
- Jira Reference (also in PR title): OPSEXP-2758
A new version of setuptools has been released which doesn't wreak the havoc for libraries still using the now deprecated feature.
https://github.com/pypa/setuptools/blob/main/NEWS.rst#v7210
=> OPSEXP-2758 Drop workaround for setuptools incident after upstream fix

docs/README.md
Document how to wait for PR approval before running a workflow for dependabot PRs.
=> Add recipe to wait for dependabot PR approval before running wf

docs/README.md
- Jira Reference (also in PR title):
Just updating the README to mention the correct latest way of creating Teams Webhooks as the previously documented one is referring to deprecated Webhooks that are going to reach EoL by end of year.
=> AAE-33027 Update docs to create Teams Webhooks

.github/workflows/updatecli.yml
There is no need to run updatecli workflow upon a release like in https://github.com/Alfresco/alfresco-build-tools/actions/runs/17062594838
=> Fix updatecli workflow trigger after a release
