.github/actions/setup-helm-docs/action.yml
.github/actions/setup-jx-release-version/action.yml
.github/actions/setup-rancher-cli/action.yml
.github/actions/setup-updatebot/action.yml
.github/actions/setup-yq/action.yml
.pre-commit-config.yaml
.travis.aws-iam-authenticator_install.yml
.travis.java_config.yml
.travis.maven_config.yml
.travis.pre-commit.yml

Add to the repo the GitHub Actions equivalent of some of the Travis config snippet to import using composite run steps actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

AAE-4703 add shared GitHub Actions

---

.travis.docker-buildx_install.yml
.travis.yml

Add https://github.com/docker/buildx

Add docker-buildx Travis CI install

---

README.md

OPSEXP-1357 add placeholders in readme for further extension

---

README.md

OPSEXP-1357 Add migrate to actions table in README

---

.github/actions/pre-commit/action.yml
.github/workflows/test.yml
README.md

OPSEXP-1358 Add pre-commit action

---

.github/actions/setup-yq/action.yml
.travis.yq_install.yml

This adds the possibility to parse XML files using `yq`. I.e:
```
yq -p=xml e '.project.properties."activiti-cloud.version"' pom.xml
```

Bump yq from version `4.6.1` to `4.24.4`

---

README.md

as suggested in https://github.com/Alfresco/alfresco-build-tools/pull/36#issuecomment-1093355702

Suggest more maintained action for auto cancel branch builds

---

README.md

as suggested in https://github.com/Alfresco/alfresco-build-tools/pull/37#issuecomment-1093357413

Suggest specific action for buildx support

---

README.md

OPSEXP-1491 add workflow concurrency snippet

---

.github/actions/update-deployment-runtime-versions/action.yml
.github/actions/update-pom-to-next-pre-release/action.yml
.github/workflows/build-and-tag-maven.yml
.github/workflows/publish-artifacts-for-veracode.yml
README.md

Needed by:
- https://github.com/Alfresco/alfresco-modeling-service/pull/284
- https://github.com/Alfresco/alfresco-process-connector-services/pull/1560
- https://github.com/Alfresco/alfresco-process/pull/913
- https://github.com/Alfresco/alfresco-deployment-service/pull/556

AAE-8964 add reusable action and workflows

---

.github/actions/travis-env-load/action.yml
.github/tests/travis-env-load/env.yml
.github/workflows/test.yml
README.md

OPSEXP-968 Add action to load travis yml with env.global section

---

README.md
release.sh

OPSEXP-1539 Add a release script

---

.github/actions/calculate-next-internal-version/action.yml
.github/actions/setup-helm-docs/action.yml
.github/actions/setup-jx-release-version/action.yml
.github/actions/setup-terraform-docs/action.yml
.github/actions/update-chart-version/action.yml
.github/actions/update-pom-to-next-pre-release/action.yml
.github/workflows/build-and-tag-maven.yml
.github/workflows/helm-publish-new-package-version.yml
.pre-commit-config.yaml
.travis.aws-iam-authenticator_install.yml
.travis.helm-docs_install.yml
.travis.helm.yml
.travis.helm_install.yml
.travis.java.yml
.travis.java_docker.yml
.travis.jq_install.yml
.travis.kcadm_install.yml
.travis.kubepug_install.yml
.travis.kubernetes_install.yml
.travis.rancher_cli_install.yml
.travis.rancher_cli_kubernetes_config.yml
.travis.terraform-docs_install.yml
.travis.terraform_install.yml
.travis.tflint_install.yml
.travis.yq_install.yml

First time using the release script OPSEXP-1539

Release v1.7.0

---

.github/workflows/versions-propagation-auto-merge.yml

Pull requests created to propagate versions should be automatically approved and merged

AAE-9367 handle auto merge of propagation PRs

---

.github/actions/send-slack-notification/action.yml

Allow custome message in block when posting to slack (required for OPSEXP-1623)

add custom message support and special case for issues

---

README.md

OPSEXP-1718 Debug with ssh action

---

.github/actions/dbp-charts/publish-chart/action.yml
.github/actions/dbp-charts/publish-chart/publish_chart.sh
.github/actions/dbp-charts/verify-compose/action.yml
.github/actions/dbp-charts/verify-compose/docker_compose.sh
.github/actions/dbp-charts/verify-helm/action.yml
.github/actions/dbp-charts/verify-helm/helm_install.sh

OPSEXP-1545 Scripts refactoring

---

.github/actions/dbp-charts/verify-compose/action.yml

make docker hub creds and file optional

---

.github/actions/pre-commit/action.yml

fix previous PR where a bug slipped the tests and reviews

OPSEXP-1746: fix broken pre-commit action

---

.github/actions/maven-deploy-file/action.yml

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project standalone-pom: Specified side artifact  does not exist -> [Help 1]
```
when not specifying any files/classifiers/types

Fixup deploy-file when deploying a single file

---

.github/actions/dbp-charts/verify-helm/action.yml
.github/actions/dbp-charts/verify-helm/helm_install.sh

OPSEXP-1746: helm skip co

---

README.md

* minor cleanups in adiacent paragraphs

Add paragraph about enabling back build output

---

.github/actions/maven-build-and-tag/action.yml

Adds ability to define restore keys on the cache

AAE-10961: improve maven cache logic

---

release.sh

OPSEXP-1782 Fixup release script with more specific sed command

---

.github/actions/validate-maven-versions/action.yml
README.md

Fixes https://alfresco.atlassian.net/browse/AAE-10543

fix(AAE-10543): add validate-maven-versions Github action

---

.github/actions/send-slack-notification/action.yml
.github/workflows/test.yml

OPSEXP-1806
this is just a quick fix to release and unblock the depending pipelines and will work on something improved before moving on
ref https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-2
tested manually:

OPSEXP-1806 Fixup slack notification

---

.github/actions/dbp-charts/verify-helm/action.yml
.github/actions/dbp-charts/verify-helm/helm_install.sh

* dump dependent actions to fix warnings
OPSEXP-1828

OPSEXP-1828 verify-helm: always echo the values file path

---

docs/security.md

OPSEXP-1742 Document quickstart for detect-secrets tool

---

docs/README.md
docs/security.md
docs/travis.md

* travis and migrate from travis to a dedicated travis.md
* moved some security related paragraphs to security.md
* added links from the main readme

Move travis docs to a dedicated section

---

.github/actions/dbp-charts/publish-chart/action.yml
.github/actions/dbp-charts/publish-chart/publish_chart.sh

OPSEXP-1796 Simplify publish-chart release skipping tags

---

.github/actions/load-release-descriptor/action.yml

fix(load-release-descriptor): add notes-start-tag parameter

---

.github/workflows/build-and-release-maven.yml

Generalize reusable workflow for Maven build and release.

ACS-4456 Generalize reusable workflow for Maven build and release

---

.github/actions/pre-commit/action.yml
docs/README.md

Ref: OPSEXP-2004
Tested in https://github.com/Alfresco/alfresco-helm-charts/pull/8

OPSEXP-2004 Add auto-commit support for pre-commit action

---

.github/actions/setup-kind/action.yml
docs/README.md

OPSEXP-1881 setup-kind with configurable node-image

---

.github/actions/dbp-charts/verify-compose/action.yml
.github/actions/dbp-charts/verify-helm/action.yml
docs/README.md

OPSEXP-2109 Bump acs-deployment related actions

---

.github/actions/docker-dump-containers-logs/action.yml
docs/README.md

- Added new action docker-dump-containers-logs allowing to store Docker containers logs.

ACS-5201: ARM64 ACS Packaging CI failure

---

.pre-commit-hooks.yaml

OPSEXP-2152 Add hook for running helm dep build

---

.github/actions/maven-build-and-tag/action.yml

This PR adds the inputs and a step to login into ghcr.io in order to pull images for `testcontainers`.

[AAE-15460] Add ghcr login for Maven build

---

.github/actions/pmd/action.yml
.github/actions/pmd/create-summary.py
.github/actions/pmd/delta-scan.sh
docs/README.md

An example of the summary artifact is at the bottom of the page on this build: https://github.com/Alfresco/alfresco-community-repo/actions/runs/5520727195

PRODENG-222 Create summary of PMD scan.

---

.github/workflows/release.yml

- Jira Reference (also in PR title): OPSEXP-1709
Reflect that the release commit is pushed using alfresco-build PAT by using proper commit author instead of the default github-actions-bot

OPSEXP-1709 Release commit as alfresco-build

---

.github/actions/docker-build-image/action.yml
docs/README.md

- Jira Reference (also in PR title): AAE-17459

AAE-17459: documentation + comment fixes

---

.github/dependabot.template.yml
.github/dependabot.yml
.pre-commit-config.yaml
update-dependabot.sh

- Jira Reference (also in PR title): AAE-18008

AAE-18008: Make dependabot update actions

---

.github/dependabot.template.yml
.github/dependabot.yml

There are those multiple actions which follows the same version as they are released all together, better update them in a single dependabot PR
https://github.com/Alfresco/alfresco-build-tools/pull/416
https://github.com/Alfresco/alfresco-build-tools/pull/417

Group dflook action bumps

---

.github/actions/dbp-charts/verify-helm/action.yml
.github/actions/send-teams-notification/action.yml

- Jira Reference (also in PR title):
Relates to https://github.com/Alfresco/alfresco-build-tools/pull/420#discussion_r1413517618, depends on https://github.com/HylandSoftware/github-actions-sha-convert/pull/4

AAE-18783: fix version comment on some actions

---

.github/workflows/release.yml

avoid failure like https://github.com/Alfresco/alfresco-build-tools/actions/runs/8812930250

do not try to release on dependabot pr close

---

.github/workflows/updatecli.yml
.updatecli/templates/github_releases.yaml

* trigger workflow on push when changing configs
* namespace all the required variables
* use dynamic default branch name

Fix updatecli workflow

---

.github/actions/pre-commit/action.yml
.github/actions/setup-pysemver/action.yml
.github/workflows/test.yml

Fix test workflow which is affected by https://github.com/pypa/setuptools/issues/4519 but I can't understand why changing the invokation order fix the issue :|

Fix failure in test workflow

---

.pre-commit-config.yaml
check_readme.sh
docs/README.md

Make sure there is at least an entry in the README for each action present in this repository.

Add README entries check

---

docs/README.md

As follow up of https://github.com/Alfresco/alfresco-build-tools/pull/852
- Jira Reference (also in PR title):

AAE-29492 Fix README alphabetical order

---

.github/workflows/updatecli.yml

- Jira Reference (also in PR title): OPSEXP-3066

OPSEXP-3066 Use setup-updatecli in the local workflow

---

.github/workflows/updatecli.yml
.updatecli/templates/github_releases.yaml

see for example https://github.com/Alfresco/alfresco-build-tools/pull/961/commits
enable automerge so I just need to approve the PR and will merge upon successfull build

Fix commit author for updatecli PRs

---

docs/README.md

Document a community action that can be used to easily provide contextual PR comments with build results.

OPSEXP-3126 Document community action to create/update pr comments

---

.github/actions/calculate-next-internal-version/action.yml
.github/actions/dbp-charts/publish-chart/action.yml
.github/actions/dbp-charts/verify-helm/action.yml
.github/actions/enforce-pr-conventions/action.yml
.github/actions/get-build-info/action.yml
.github/actions/github-check-upcoming-runs/action.yml
.github/actions/github-deployment-create/action.yml
.github/actions/helm-integration-tests/action.yml
.github/actions/helm-publish-chart/action.yml
.github/actions/helm-release-and-publish/action.yml
.github/actions/helm-update-chart-version/action.yml
.github/actions/maven-build-and-tag/action.yml
.github/actions/maven-build/action.yml
.github/actions/maven-dependency-scan/action.yml
.github/actions/maven-release/action.yml
.github/actions/maven-tag/action.yml
.github/actions/reportportal-prepare/action.yml
.github/actions/send-slack-notification-slow-job/action.yml
.github/actions/send-slack-notification/action.yml
.github/actions/send-teams-notification/action.yml
.github/actions/setup-helm-docs/action.yml
.github/actions/setup-jx-release-version/action.yml
.github/actions/setup-terraform-docs/action.yml
.github/actions/setup-updatecli/action.yml
.github/actions/sonar-scan-on-built-project/action.yml
.github/actions/update-pom-to-next-pre-release/action.yml
.github/workflows/build-and-release-maven.yml
.github/workflows/helm-publish-new-package-version.yml
.github/workflows/terraform.yml

Manually merging tag changes which got lost during v8.25.0 release

Release v8.25.0

---

.github/copilot-instructions.md
docs/README.md
release.sh

Since we already implement this for actual actions, updating the documentation should be straightforward. This will make it easier for users to copy and paste the relevant information.

Release script update version references in markdown files
